### ISSUE TITLE
Where to get game assets?

### ISSUE THREAD

**Issue by mewmew** [miketmoore/zelduh#1]
I'd love to try running this game, but can't quite figure out how to get the game assets. Where may they be located?

Cheers,
/u

```
build room configurations...
panic: open assets/tilemaps/overworldOpen.tmx: no such file or directory

goroutine 5 [running]:
main.parseTmxFile(0xc42001a0c0, 0x21, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/u/goget/src/github.com/miketmoore/zelduh/cmd/zelduh/zelduh.go:1233 +0x186
main.loadTmxData(0xc420430090)
	/home/u/goget/src/github.com/miketmoore/zelduh/cmd/zelduh/zelduh.go:1225 +0x1ca
main.run()
	/home/u/goget/src/github.com/miketmoore/zelduh/cmd/zelduh/zelduh.go:333 +0x11c5
github.com/faiface/mainthread.Run.func1(0x713178, 0xc42007a060)
	/home/u/goget/src/github.com/faiface/mainthread/mainthread.go:37 +0x27
created by github.com/faiface/mainthread.Run
	/home/u/goget/src/github.com/faiface/mainthread/mainthread.go:36 +0xb2
```

**Comment by miketmoore** [comment]
Hi @mewmew, thanks for you interest! I added the assets back just now, in db7027f2e1a1a6472c8324700641cec9605f9496

I also plan on publishing releases to https://miketmoore.itch.io/zelduh over time.

**Comment by mewmew** [comment]
Cool. It looks great!

Got it working with rev db7027f.

![2018-04-23-105828_800x767_scrot](https://user-images.githubusercontent.com/1414531/39116690-59eb1b7a-46e5-11e8-99e1-e65eee679480.png)

**Comment by miketmoore** [comment]
Awesome, thanks!
